### ISSUE TITLE
Running update_provider.yml returns an authentication error

### ISSUE THREAD

**Issue by pavelzag** [dkorn/manageiq-ansible-module#47]
After running an Ansible Playbook to update a provider I am getting the following message:

```
ansible-playbook update_provider_pavel.yml 
 [WARNING]: provided hosts list is empty, only localhost is available


PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [Add Openshift Containers Provider to ManageIQ] ***************************
changed: [localhost]

TASK [debug] *******************************************************************
ok: [localhost] => {
    "result": {
        "changed": true, 
        "msg": "Failed to validate provider Openshift 3 after update. Authentication: {'bearer': (u'Valid', u'Ok')}", 
        "provider_id": 5, 
        "updates": {
            "Added": {}, 
            "Removed": {}, 
            "Updated": {
                "default": {
                    "hostname": "something_different.redhat.com"
                }
            }
        }
    }
}

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=1    unreachable=0    failed=0   
```

The provider itself was updated in UI

Running the same against an older code doesn't yield such error

**Comment by cben** [comment]
Pavel, can you check what the manageiq UI shows on the provider's page?  Auth status, last refresh status? 

@dkorn I think we timed out waiting for validation? In any case our message here is confusing, "Valid, Ok" doesn't explain what's the problem.

**Comment by pavelzag** [comment]
Hi Beni.
I am getting the following values:


Bearer Authentication	Valid - 8 Minutes Ago
Hawkular Authentication	Valid - 10 Minutes Ago
Last Metrics Collection	Success - 2 Minutes Ago
Last Refresh	
Success - 7 Minutes Ago

**Comment by cben** [comment]
Good, so the module just timed out waiting for auth validation.

We need a better message, and possibly a tunable timeout and maybe not
treating timeout as error, as blocking for over a minute is not always
desirable.
(If validation does complete and fails, that will remain an error.)

Perhaps having more `state` values, like `added` vs `validated` vs
`refreshed` would be good.  Then one could add providers quickly, do other
stuff, then only when needed block for validation/refresh.

I also wonder if API could offer immediate validation instead of queueing
it.

On Dec 28, 2016 8:42 AM, "Pavel Zagalsky" <notifications@github.com> wrote:

Hi Beni.
I am getting the following values:

Bearer Authentication Valid - 8 Minutes Ago
Hawkular Authentication Valid - 10 Minutes Ago
Last Metrics Collection Success - 2 Minutes Ago
Last Refresh
Success - 7 Minutes Ago

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/dkorn/manageiq-ansible-module/issues/47#issuecomment-269433895>,
or mute the thread

**Comment by pavelzag** [comment]
Validation is working with the other modules (user, provider and custom attributes) but not here. Why's that?

**Comment by cben** [comment]
When you add a provider, manageiq queues a background task to validate it
can actually connect to it with the given credentials.
The manageiq_provider module waits for this to complete — the purpose is
module should succeed if validation passed, give an error if it failed.
But the module gives up if it takes too long (currently 50sec I think),
which is what happened here.

(Deleting providers is also a background task, but ansible module doesn't
wait for it to complete.)

Users, custom attributes do not AFAIK involve any background task.

**Comment by pavelzag** [comment]
@cben 
This is weird, I have a test that runs before that adds a provider and it succeeds.
How can this be solved?

**Comment by cben** [comment]
> This is weird, I have a test that runs before that adds a provider and it succeeds.

I'm not sure I understand what you mean, but first the module only tries to check validation since #21, second note this is not deterministic, validation should typically finish within the ~1min we give it but sometimes may time out. (*)

We're working on a PR changing behavior when module gives up waiting for validation:
 1. will give clear message
 2. have the ansible module succeed (as long as all endpoints — main & hawkular — either succeeded or are still validating.  if one completed in time with failure, module will fail, because we know the provider is not in a good state.)
Do you consider this reasonable fix?

(*) From the output in your first comment, it looks like you only updated the hostname.  If you update host/port of existing provider, but not token, you also hitting bug https://github.com/ManageIQ/manageiq/issues/13167, where ManageIQ simply won't re-validate the auth => the ansible module will deterministically poll for the ~1min and give up.  We'll fix that at some point...

**Comment by cben** [comment]
Obsolete.
In rewritten module we got into ansible/ansible, we dropped validation entirely, pending API improvements https://github.com/ManageIQ/manageiq-api/issues/28.
